### ISSUE TITLE
Add support for sidc code lookup

### ISSUE THREAD

**Issue by topowright** [Esri/military-symbology#178] opened 2017-06-15 18:04 UTC
Military users need the ability to use the Military Symbol Editor by looking up symbols based on thier SIC code. 

This is an exmample code that does not work:  SFG-UCI----D---
Here is a link to a application that can show you what the symbol should look like. 
https://spatialillusions.com/unitgenerator.html#SFG-UCI----D---

This is where the search capability should be: 

![image](https://user-images.githubusercontent.com/5488313/27195485-cb39aba4-51bb-11e7-9541-f5dbba374911.png)

Update based on #182:  Add ability to search based on keys like ArcGIS Pro in the Symbology Pane to support SIDC

**Comment by Dbarnes1** [comment] 2017-06-15 18:25
This is already possible, although in 2525B Change 2 there seems to be inconsistency across the industry as to whether the last 3 characters should be --- or ***

If you look in the tags for particular symbols, you'll see that we have gone with the *** option![image](https://user-images.githubusercontent.com/13024357/27195648-6aef3f2e-51bc-11e7-9c7a-002369948e6a.png)

The action item on this would be to look at mil2525d.stylx or mil2525c_b2.stylx and edit the tags to improve the UX

**Comment by topowright** [comment] 2017-06-19 04:09
@Dbarnes1 I want to capture the some of the issues that we were able to understand from talking the other day. 

Currently we as a team have two examples of data coming in from customers using --- and not ***. Those customers are the USMC customer that you saw in June 2017 and the DDS message examples that came from an exercise with the US Army. Being that DDS is one of the main ways that DCGS-A shares messages and they use --- I think it would make sense for us to pivot.  We also found out that taking away parts of the code did not allow the symbol to be drawn using just the first part of the SIDC. This is also what was found form @NatalieCampos ran into on issue #180.

**Comment by csmoore** [comment] 2019-08-16 16:31
Added ability to search by full SIDC in PR: #390 

Note the search will find the base symbol / style item on the search pane. It should look like this with PR:

![image](https://user-images.githubusercontent.com/3090809/63182657-0d3bfe00-c021-11e9-852e-df53d665fa18.png)

**Comment by dfoll** [comment] 2019-09-19 15:08
Works as designed. MSE searches only for the base symbol. If there is ever a requirement to search for an entire SIDC and populate fields based on the SIDC pieces, that will require focused workflow design and a new issue.

**Comment by dfoll** [comment] 2019-09-19 16:08
### Doc QC:
- [ ]  [Defense Whats new]() -- after [PR 8017](https://github.com/ArcGIS/arcgis-solutions-website/pull/8017) is reviewed and merged

**Comment by lfunkhouser** [comment] 2019-09-20 14:51
verified in PDF MT 341 and MSE 147 and Resources online, PR merged and will wait until next build to pick up/verify What's New.

**Comment by lfunkhouser** [comment] 2019-09-20 21:58
verified in what's new - closing.

**Closed by lfunkhouser** 2019-09-20 21:58 UTC
Labels: A-feature, E-verified, V - MT 3.6, V - Pro 2.2
