### ISSUE TITLE
MSE needs to check string length in Labels Tab

### ISSUE THREAD

**Issue by kgonzago** [Esri/military-symbology#327] opened 2019-01-07 18:50 UTC
#### Issue
A message dialog box is displayed when a user tries to add a symbol to the map.
![image](https://user-images.githubusercontent.com/6391826/50786749-66b99e80-1282-11e9-8a02-dec1006ad656.png)

#### Repro Steps
In the Labels tab of MSE:
1. Enter appropriate metadata for a symbol 
![image](https://user-images.githubusercontent.com/6391826/50786821-9a94c400-1282-11e9-974d-335ec04b22e3.png)
2. Click on `Add to Map` to add symbol to the map
3. Observer dialog box

#### Possible Cause
This is a possible field length issue. MSE will need to inform user that a value exceed the length of a particular metadata field.

**Comment by csmoore** [comment] 2019-01-09 21:59
Addressed in PR #328 - should look like this now and not allow string lengths that will cause the feature store step to fail:

![image](https://user-images.githubusercontent.com/3090809/50930645-8392d500-142e-11e9-8d84-bfbcb7ddaa31.png)

**Comment by BobBooth** [comment] 2019-01-10 17:13
This is now highlighting the box if the length of the string is too long, and providing a popup if you hover over the box that explains the string is too long.
However, it lets you continue typing the string into the box past that length, and it allows you to click Add to Map and add features to the map. The features get truncated strings.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/5f2a882d-6cd2-4591-b6a3-faffa21d0fa0)
It would be better if the Add to Map button included a validation step to check if any of the fields exceed the field length specified for the feature class, and pop up an error message indicating the field (or fields) that have strings that are too long.
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/77b4dbc0-a817-430c-a7ac-b71c411458af)

The idea is it would be like a web form, where when you click "Submit" and your credit card number is wrong, or some required field is not filled out, that you can't just proceed anyway, but get feedback about what the problem is.

**Comment by BobBooth** [comment] 2019-01-10 17:19
I am having second thoughts about allowing them to continue to type any text beyond the database field length.  The default Attribute editor dialog just stops accepting text when you get to the max length.
Maybe this is a cleaner way to handle it?
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/dc92aab5-a017-45e4-891b-5a73ccd3b96e)
@kgonzago @lfunkhouser @dfoll

**Comment by kgonzago** [comment] 2019-01-10 19:07
@BobBooth I agree. Given that is the OOTB behavior, let's implement the same pattern.

**Comment by kgonzago** [comment] 2019-01-11 20:41
1. Added max length to textboxes
2. Updated tooltip message

![image](https://user-images.githubusercontent.com/6391826/51058619-60dff800-15b7-11e9-9932-3dce02990795.png)

**Comment by BobBooth** [comment] 2019-01-11 21:38
I have added a feature issue suggesting a refinement of the behavior we have now.
https://github.com/Esri/military-symbology/issues/331

**Comment by dfoll** [comment] 2019-01-16 16:11
@csmoore @kgonzago apologies, I tested and verified this previously, but today when I was doing some final checks to move this to done I noticed one small issue.

In the input for Unique Designation you can type 30 characters before you get the warning that you have reached the maximum allowable length, this is correct, however when you create the feature, only the first 29 characters get committed.

![image](https://user-images.githubusercontent.com/5322669/51261961-4fb03600-197f-11e9-92c7-6732b5d4e66d.png)

**Comment by kgonzago** [comment] 2019-01-16 20:58
Fix to take max length of value entered by user is in this [PR](https://github.com/Esri/military-symbology/pull/334). 

![image](https://user-images.githubusercontent.com/6391826/51278067-8bf78c80-19a7-11e9-983c-013f3923e54c.png)

**Comment by csmoore** [comment] 2019-01-17 15:15
PR #334 Merged and new dev built to test at `\\redarchive2\disl\Development\Commercial\Solutions\DefenseSolutions\MilitarySymbolEditor\January2019\Dev\32\`

**Comment by csmoore** [comment] 2019-01-18 14:06
Ready for retest with PR #337

**Closed** 2019-01-18 21:19 UTC
Labels: A-bug, B-low, E-verified, S-Military Symbol Editor, T-Military Symbology, V -  Pro 2.1, V - MT 3.3
